### PR TITLE
You can now use / to quickly enter a command

### PR DESCRIPTION
**Pull request by raphydaphy**
I added a keybind for chatting commands (`/`), which opens the chat with a slash already entered, saving you from having to press Enter and then Slash to write commands.

Also reverted Ellpeck's furnace inventory change.

### CODE REVIEW

**Comment by canitzp** [comment]
Im fine with this

**Comment by raphydaphy** [comment]
How many reviews/confirmations should we wait for to merge pr's in general? Since this is the first it would be good to establish basic rules for all now.

**Comment by canitzp** [comment]
I think all Contributer except Ellpeck should know about it and if there aren't coming any complaints, the author can merge it

**Comment by raphydaphy** [comment]
alright so just like that ^^

**Comment by canitzp** [comment]
yeah

**Comment by Quarris** [comment]
Looks good

**Pull request merged**
